# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
 
- task: HelmInstaller@0
  inputs:
    helmVersion: 'latest'
    installKubectl: true
    
- task: HelmDeploy@0
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: 'Visual Studio Enterprise(f3757d8c-c242-4598-816e-4d9c38bf927d)'
    azureResourceGroup: 'myResourceGroup'
    kubernetesCluster: 'myAKSCluster'
    namespace: 'myaksdemo'
    command: 'install'
    chartType: 'FilePath'
    chartPath: './aksDemoHelm'
    overrideValues: 'aksdemo.version=20'
    azureSubscriptionForACR: 'Visual Studio Enterprise(f3757d8c-c242-4598-816e-4d9c38bf927d)'
    azureResourceGroupForACR: 'myResourceGroup'
    azureContainerRegistry: 'xudongacr.azurecr.io'
