apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
spec:
  selector:
    istio: istio-ingressgateway  # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    tls:
      httpsRedirect: true # redirect http request to https
    hosts:
    - zyxhome.top
    - www.zyxhome.top
    - 192.168.88.2
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: istio-ingressgateway-cert
    hosts:
    - zyxhome.top
    - www.zyxhome.top
    - 192.168.88.2