apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.weatherForecastWeb.name }}-virtualservice
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.gateway.name }}
  http:
  - match:
    - uri:
        prefix: /api/WeatherForecast
      ignoreUriCase: true
    route:
    - destination:
        host: {{ .Values.weatherForecastApi.name }}
        port:
          number: {{.Values.weatherForecastApi.service.port}}
        subset: subset-{{ .Values.version }}
  - match:
    - uri:
        prefix: /
      ignoreUriCase: true
    route:
    - destination:
        host: {{ .Values.weatherForecastWeb.name }}
        subset: subset-{{ .Values.version }}
  