apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.portalHome.name }}-virtualservice
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.gateway.name }}
  tls:
  - match:
    - sniHosts: ["192.168.88.2", "www.zyxhome.top"] 
    - uri:
        prefix: /swagger
      ignoreUriCase: true   
    route:
    - destination:
        host: {{ .Values.weatherForecastApi.name }}
        port:
          number: {{.Values.weatherForecastApi.service.port}}
        subset: subset-{{ .Values.version }} 
  - match:
    - sniHosts: ["192.168.88.2", "www.zyxhome.top"]  
    - uri:
        prefix: /api
      ignoreUriCase: true
    route:
    - destination:
        host: {{ .Values.weatherForecastApi.name }}
        port:
          number: {{.Values.weatherForecastApi.service.port}}
        subset: subset-{{ .Values.version }}  
  
  - match:
    - sniHosts: ["192.168.88.2", "www.zyxhome.top"]
    - uri:
        prefix: /
      ignoreUriCase: true  
    route:
    - destination:
        host: {{ .Values.portalHome.name }}
        port:
          number: {{.Values.portalHome.service.port}}
        subset: subset-{{ .Values.version }}  