apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.portalHome.name }}-{{ .Values.version }}
spec:
  replicas: {{ .Values.portalHome.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.portalHome.name }}
      version: {{ .Values.version | quote }}
  template:
    metadata:      
      labels:
        app: {{ .Values.portalHome.name }}
        version: {{ .Values.version | quote }}
    spec:
      containers:
        - name: {{ .Values.portalHome.name }}          
          image: "{{ .Values.portalHome.image.repository }}:{{ .Values.version }}"
          imagePullPolicy: {{ .Values.portalHome.image.pullPolicy }}
          ports:
            - containerPort: 80
              protocol: TCP     
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80  