apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.weatherForecastWeb.name }}-virtualservice
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.gateway.name }}
  http:
  - route:
    - destination:
        host: {{ .Values.weatherForecastWeb.name }}
        subset: subset-{{ .Values.weatherForecastWeb.version }}