apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.weatherForecastApi.name }}-{{ .Values.version }}
spec:
  replicas: {{ .Values.weatherForecastApi.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.weatherForecastApi.name }}
      version: {{ .Values.version | quote }}
  template:
    metadata:      
      labels:
        app: {{ .Values.weatherForecastApi.name }}
        version: {{ .Values.version | quote }}
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: {{ .Values.weatherForecastApi.name }}          
          image: "{{ .Values.weatherForecastApi.image.repository }}:{{ .Values.version }}"
          imagePullPolicy: {{ .Values.weatherForecastApi.image.pullPolicy }}
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            {{- range $key, $value := .Values.weatherForecastApi.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}     
          livenessProbe:
            httpGet:
              path: /api/WeatherForecast
              port: 80
          readinessProbe:
            httpGet:
              path: /api/WeatherForecast
              port: 80  