apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.aksdemo.name }}-virtualservice
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.gateway.name }}
  http:
  - route:
    - destination:
        host: {{ .Values.aksdemo.name }}
        subset: subset-{{ .Values.aksdemo.version }}