gateway:
  name: aksdemo-gateway

weatherforecast-web:
  name: weather-forecast-web
  version: v1
  replicas: 1
  image:
    repository: xudongacr.azurecr.io/weatherForecastWeb
    pullPolicy: IfNotPresent
  service:
    port: 80