gateway:
  name: aksdemo-gateway

weatherForecastWeb:
  name: weatherForecastWeb
  version: v1
  replicas: 1
  image:
    repository: xudongacr.azurecr.io/weatherForecastWeb
    pullPolicy: IfNotPresent
  service:
    port: 80