gateway:
  name: weather-forecast-gateway

weatherForecastWeb:
  name: weather-forecast-web
  version: v1
  replicas: 1
  image:
    repository: xudongacr.azurecr.io/weatherforecastweb
    pullPolicy: IfNotPresent
  service:
    port: 80

weatherForecastApi:
  name: weather-forecast-api
  version: v1
  replicas: 1
  image:
    repository: xudongacr.azurecr.io/weatherforecastapi
    pullPolicy: IfNotPresent
  service:
    port: 80