gateway:
  name: weather-forecast-gateway

version: v1

portalHome:
  name: portal-home
  replicas: 1
  image:
    repository: xudongacr.azurecr.io/portal-home
    pullPolicy: IfNotPresent
  service:
    port: 80

weatherForecastApi:
  name: weather-forecast-api
  replicas: 1
  image:
    repository: xudongacr.azurecr.io/weatherforecastapi
    pullPolicy: IfNotPresent
  service:
    port: 80
