gateway:
  name: weather-forecast-gateway
  jwtConfig:
    issuer: zyxHome
    jwk: |
      { "keys":[{"kty": "EC","use": "sig","crv": "P-256","kid": "ic1EYreC1UwexTSowT0K6kYrstk_Hr-DWWj0KS3QHLU","x": "28QJtSh28OVqJ-mUEuAPVfwV3iIkX9AVrfNTu2o8SfY","y": "9jwkgqnMYPGIm-LSr8q5n60EiqvXL8DFgSiheLII9JQ","alg": "ES256"}]}


version: v1

portalHome:
  name: portal-home
  replicas: 1
  image:
    repository: zxd882002/portal-home
    version: "1680253628"
    pullPolicy: IfNotPresent
  service:
    port: 80

weatherForecastApi:
  name: weather-forecast-api
  replicas: 1
  image:
    repository: zxd882002/weather-forecast-api
    version: "1680253628"
    pullPolicy: IfNotPresent
  env:
    ASPNETCORE_URLS: http://+:80
    WeatherForecastAPI__RedisEndPoint: redis-master.redis.svc.cluster.local:6379
    WeatherForecastAPI__RedisPassword: "123456"
  service:
    port: 80
