name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get tag value
      run: echo "$(date +%s)" >> $Tag
    - name: Build the Docker image for weatherforcast
      working-directory: ./src/WeatherForecastAPI
      run: docker build . --file Dockerfile --tag zxd882002/weather-forecast-api:$Tag
    - name: Push the image to docker hub
      run: docker push zxd882002/weather-forecast-api:$Tag
